### ISSUE TITLE
 Flickr_30k.trainimages.txt and Flickr_30k.testimages.txt files.

### ISSUE THREAD

**Issue by MikhailovSergei** [anuragmishracse/caption_generator#10]
Hello, do u have the Flickr_30k.trainimages.txt and Flickr_30k.testimages.txt files. I can't find this files in anywhere=( In official web it's unable to download. I have image I need just this files

**Comment by anuragmishracse** [comment]
I guess, you need to request for captions at https://illinois.edu/fb/sec/7805261 .

**Comment by MikhailovSergei** [comment]
I am not sure why, but in China it's web not work(
