### ISSUE TITLE
Missing InceptionV3

### ISSUE THREAD

**Issue by crowoy** [anuragmishracse/caption_generator#13]
The `prepare_dataset.py` has finished. I am trying to run the `train_model.py` however, it is giving me the following error:

`ImportError: No module named inception_v3`

I thought that the `inception_v3` module was included in Tensorflow?

**Comment by anuragmishracse** [comment]
I understand. When I was implementing it, that time keras didn't have these modules included in the package and provided it as standalone scripts. 

Could you fix the import statements and send a pull request?
FYI, you'll find these models in `keras.applications`.

**Comment by MikhailovSergei** [comment]
Hi, take from here https://github.com/fchollet/keras/tree/master/keras/applications

**Comment by crowoy** [comment]
Done

**Comment by anuragmishracse** [comment]
Thanks! I hope you were able to make it work.

**Comment by MikhailovSergei** [comment]
Where we can take the prepare data set file for mscoco
