### ISSUE TITLE
Generating Captions on non-Flickr8k images

### ISSUE THREAD

**Issue by crowoy** [anuragmishracse/caption_generator#16]
How do you go about generating captions on images of your choice?

The testing code seems to reply on the pre-generated `encoded_images.py` file, which only contains encodings for Flickr8k images in this case. The `prepare_dataset.py` file does not seem easy to adapt to encode images of your choice into `encoded_images.py`.

Any help would be appreciated.

**Comment by anuragmishracse** [comment]
@crowoy You have functions for that. In the `prepare_dataset.py`, you can use the functions `load_encoding_model()` and `get_encoding(model, image_path)` to get the encoded vector of an image. Once you have the vector, just tweak the test_model.py or use function in it to get the predictions for the image.
