### ISSUE TITLE
can you please share a copy of your 'weights-improvement-XX.hdf5'

### ISSUE THREAD

**Issue by chansigit** [anuragmishracse/caption_generator#2]
I find the training takes a lot of time. Can you share a copy of your model weight?
We hope to test if we deploy your code successfully.
Up to now, we only run 1 epoch and the test result shows not a single caption can be produced. 
Is this normal? will more epoch rounds improve brings reasonable output instead of empty output?
Thank you for your cool work.

**Comment by Shaoming-Song** [comment]
Hi, I have deployed this model rencently on my own image caption dataset(with some modifications). And I found that if you change the batch_size in train_model.py from 32 to 1024 or some other bigger values, this project will train 1 epoch in several minutes and the after 30 or more epochs the results are really good.
Hope this experience can help you.

**Comment by anuragmishracse** [comment]
@chansigit Hi. Yes, this is normal. Training the model takes time, and the output will improve as the model trains. However, as @Shaoming-Song said, increasing the batch_size would decrease per epoch time, resulting in good captions getting generated quickly, but the quality would not be that great. The batch_size can be tweaked as per your needs.
