### ISSUE TITLE
how to get Flicker8k_dataset

### ISSUE THREAD

**Issue by mohitbindal10** [anuragmishracse/caption_generator#27]
how to get the images that is required to be stored in Flicker8k_Dataset folder to run prepare_data.py
please help my email id is : mohitbindal98@gmail.com

**Comment by anuragmishracse** [comment]
Hi, you can request for the dataset here https://forms.illinois.edu/sec/1713398
OR
You can download from the publicly available http://nlp.cs.illinois.edu/HockenmaierGroup/8k-pictures.html
