### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by iland5** [anuragmishracse/caption_generator#6]
Hi,

The model works good and i would like to know if you can share a pre-trained models.

Thanks

**Comment by jermenkoo** [comment]
@anuragmishracse any updates on this? It would help me as well as training it (even on a GPU) takes a long time.

**Comment by anuragmishracse** [comment]
@jermenkoo Sorry, I don't have access to the weight file now. I'll try to add the weights file, if I'm able to train a new model.
